/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_iqbal_ndkhello2_ndk_NativeLib */

#ifndef _Included_com_iqbal_ndkhello2_ndk_NativeLib
#define _Included_com_iqbal_ndkhello2_ndk_NativeLib
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_iqbal_ndkhello2_ndk_NativeLib
 * Method:    getAdd
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_iqbal_ndkhello2_ndk_NativeLib_getAdd
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_iqbal_ndkhello2_ndk_NativeLib
 * Method:    getSub
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_iqbal_ndkhello2_ndk_NativeLib_getSub
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_iqbal_ndkhello2_ndk_NativeLib
 * Method:    getMult
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_iqbal_ndkhello2_ndk_NativeLib_getMult
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_iqbal_ndkhello2_ndk_NativeLib
 * Method:    getDivi
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_iqbal_ndkhello2_ndk_NativeLib_getDivi
  (JNIEnv *, jclass, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
